app:
  jwt:
    secret-key: "WJKEHRFIOU2W4HJGUIO2UIOTHG2890RTU90UG90KWHJFG902UJPF2NKJWNFIHQWNFGUIO3478957823YNVKMSKOLTM2893450IOW3JK924IUTG90I2U09GU029TU9012"

server:
  port: 8082

spring:
  application:
    name: AuthService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka