supabase:
  url: https://sbyvpbceneoqeaxgiigt.supabase.co
  service:
    role:
      key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieXZwYmNlbmVvcWVheGdpaWd0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzIzODEwNiwiZXhwIjoyMDcyODE0MTA2fQ.tnluNhwzpTfwEeQrvlSubkLqqxdqxvsZ_hqLu-_vBF8

server:
  port: 8082

spring:
  application:
    name: AuthService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka