server:
  port: 8081

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        # -->> AuthService routes <<--
        - id: AuthService
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
        - id: AuthService
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/users/**
        # -->> BookService routes <<--
        - id: BookService
          uri: lb://BOOKSERVICE
          predicates:
            - Path=/books/**
        - id: BookService
          uri: lb://BOOKSERVICE
          predicates:
            - Path=/authors/**
        - id: BookService
          uri: lb://BOOKSERVICE
          predicates:
            - Path=/literary-genres/**
        # -->> CartSerice routes <<--
        - id: CartService
          uri: lb://CARTSERVICE
          predicates:
            - Path=/cart/** 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG